### PR TITLE
Adding command line arguments for the benchmark

### PR DESCRIPTION
**Pull request by odatskov**

### CODE REVIEW

**Comment by rdemaria** [comment]
ok for me, but I would prefer to use another filename like benchmark_opencl.py ad leave bench20k.py as it is, if it is ok for you.

What do you think adding a command line option to list available opencl devices?

**Comment by odatskov** [comment]
Agree. Making the changes...

**Comment by odatskov** [comment]
Would we want to list devices and then exit or list all devices every time we run the benchmark?

**Comment by rdemaria** [comment]
I think it is better to exit. In some case if the system is not setup correctly (e.g. incompatible LD_LIBRARY_PATH) the OpenCL driver could fail.

**Comment by odatskov** [comment]
All right. Will this be enough for now?

**Comment by rdemaria** [comment]
what about this logic

```python
  if args.device:
      devices=args.device.split()
  else:
      devices=sim.TrackJobCL.get_available_devices()
  for device in devices:
    cljob = sim.TrackJobCL(particles, elements, device=device, dump_element=0)
    duration=speed(cljob,args.npart,args.nturn)
    print( f"{(args.npart*args.nturn)/duration:9.0f} particles*turns/seconds, "
          f"{args.npart} particles, {args.nturn} turns, "
          f"device '{args.device}', {cljob.ctx.devices[0].name}")
```

and removing the default="0.0" in device. In this way we can have

```
benchmark_opencl.py  !run on all devices
benchmark_opencl.py  -d 0.0 !run on first device
benchmark_opencl.py  -d "0.0 2.0" !run on selected devices
```

**Pull request merged**
